sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '6'
before_script:
  - npm prune
script:
  - node . &
  - curl localhost:4000
  - npm i -g now-pipeline
  - now-pipeline --test "npm run prod-test"
  - now-pipeline-prune
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
